export { default as BlocksRenderer } from './src/BlocksRenderer.astro';

export type {
  BlocksContent,
  BlocksRendererProps,
  BlockNode,
  TextNode,
  LinkNode,
  InlineNode,
  ParagraphNode,
  HeadingNode,
  ListNode,
  ListItemNode,
  QuoteNode,
  CodeNode,
  ImageNode,
  HorizontalLineNode,
  TableNode,
  TableRowNode,
  TableCellNode,
  TableHeaderCellNode,
  MediaEmbedNode,
  MathNode,
  DiagramNode,
  CalloutNode,
  CalloutVariant,
  DetailsNode,
  TextAlign,
  StyleValue,
  CustomBlocksConfig,
  CustomModifiersConfig,
  AstroComponentFactory,
} from './src/types';
